mysite/marvel/urls.py
from django.urls import path, include

from .views.home_login_view import HomeLoginView
from .views.dashboard_view import DashboardView
from .views.logout_view import LogoutView
from .views.search_character_view import SearchCharacterView
from .views.character_view import CharacterView

import django.contrib.auth.urls

app_name = 'marvel'
urlpatterns = [
    path('', HomeLoginView.as_view(), name='home_login'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('search_character', SearchCharacterView.as_view(), name='search_character'),
    path('character', CharacterView.as_view(), name='character'),

    #path('accounts/', include('django.contrib.auth.urls')),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('marvel/', include('marvel.urls')),
    path('admin/', admin.site.urls),
]

mysite/marvel/models/characters.py
from django.db import models
from django.utils.timezone import now

class Characters(models.Model):

    char_name = models.CharField(max_length=100)
    char_external_id = models.IntegerField(default=0)
    char_external_url = models.CharField(max_length=500)
    image_url = models.CharField(max_length=500, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    avaliable_comics = models.IntegerField(default=0)
    created_at = models.DateTimeField('date published', default=now)
    updated_at = models.DateTimeField('date updated', default=now)


    def __str__(self):
        return f'{self.char_name}' 

mysite/marvel/models/user_account.py
from django.db import models
from django.contrib.auth.models import User
from .characters import Characters

class UserAccount(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(default=0)
    favorite_character = models.ForeignKey(Characters, on_delete=models.CASCADE,  blank=True, null=True)

    def __str__(self):
        return self.user.first_name

mysite/marvel/models/user_characters.py
from django.db import models
from django.utils.timezone import now

from .characters import Characters
from .user_account import UserAccount

class UserCharacters(models.Model):

    user = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    character = models.ForeignKey(Characters, on_delete=models.CASCADE)
    char_user_alias = models.CharField(max_length=500, blank=True, null=True)
    is_favorite = models.BooleanField(default=False)
    added_at = models.DateTimeField('date added', default=now)

    def __str__(self):
        return f'{self.user.user.first_name} | {self.character.char_name} | {self.char_user_alias}' 

mysite/marvel/views/forms/character_form.py
from django import forms
from ...models.characters import Characters
from ...models.user_characters import UserCharacters

class CharacterForm(forms.Form):
    char_id = forms.IntegerField(required=True)
    char_name = forms.CharField(max_length=100, required=False)
    char_external_url = forms.CharField(max_length=500, required=False)
    image_url = forms.CharField(max_length=500, required=False)
    description = forms.CharField(max_length=500, required=False)
    avaliable_comics = forms.IntegerField(required=False)

    def add(self, request):

        char_id = self.cleaned_data['char_id']
        char_name = self.cleaned_data['char_name']
        char_external_url = self.cleaned_data['char_external_url']
        image_url = self.cleaned_data['image_url']
        description = self.cleaned_data['description']
        avaliable_comics = self.cleaned_data['avaliable_comics']


        # Verifica se o personagem já existe na base de dados
        try:
            character = Characters.objects.get(char_external_id=char_id)
        except Characters.DoesNotExist:
            # senao existe cria
            character = Characters(char_name=char_name,
                                   char_external_id=char_id,
                                   char_external_url=char_external_url,
                                   image_url=image_url,
                                   description=description,
                                   avaliable_comics=avaliable_comics
                                  )
            character.save()

        # Associa o personagem ao usuario
        user_char = UserCharacters(user=request.user.useraccount,
                                   character=character,
                                   char_user_alias=''
                                    )
        user_char.save()

        return True

    def remove(self, request):
        char_id = self.cleaned_data['char_id']

        user_char = UserCharacters.objects.get(user=request.user.useraccount,
                                               character=char_id
                                               )
        user_char.delete()

        return True

    def make_favorite(self, request):
        char_id = self.cleaned_data['char_id']

        # remove todos os favoritos
        user_chars = UserCharacters.objects.filter(user=request.user.useraccount)

        for item in user_chars:
            item.is_favorite = False
            item.save()

        # atribui favorito ao escolhido
        user_char = UserCharacters.objects.get(user=request.user.useraccount,
                                               character=char_id
                                              )
        user_char.is_favorite = True
        user_char.save()

        return True                

mysite/marvel/views/forms/login_form.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput)

mysite/marvel/views/forms/search_character_form.py
from django import forms
import requests

class SearchCharacterForm(forms.Form):
    char_name_search = forms.CharField(max_length=100, required=True)

    def search(self):
        result = {}
        char_name_search = self.cleaned_data['char_name_search']

        endpoint = 'https://gateway.marvel.com:443/v1/public/characters?apikey=9c034c15eff31760f9f9b9a34d7bf3e3&hash=2a139a7bce9a6d813ac34a0107beff33&ts=1601415510&nameStartsWith={char_name_search}'        
        url = endpoint.format(char_name_search=char_name_search)

        response = requests.get(url)
        if response.status_code == 200:  # SUCCESS
            result = response.json()
            if result['data']['total'] > 0:
                result['success'] = True
            else:
                result['success'] = False
                result['message'] = f'No entry found for {char_name_search}'

        else:
            result['success'] = False
            if response.status_code == 404:  # NOT FOUND
                result['message'] = f'No entry found for {char_name_search}'
            else:
                result['message'] = 'The Oxford API is not available at the moment. Please try again later.'
        return result

mysite/marvel/views.py
from django.shortcuts import render

# Create your views here.

mysite/marvel/views/character_view.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


from .forms.character_form import CharacterForm

class CharacterView(LoginRequiredMixin, View):
    form_class = CharacterForm
    template_name = 'marvel/dashboard.html'
    login_url = '/marvel/'
    redirect_field_name = 'redirect_to'

    def post(self, request, *args, **kwargs):
        errormessage = ''

        # delete character
        if request.POST['_method'] == "DELETE":
            form = CharacterForm(request.POST)
            if form.is_valid():
                remove_result = form.remove(request)

                return HttpResponseRedirect(reverse('marvel:dashboard', args=()))
            else:
                return render(request, self.template_name, {'errormessage': 'error on delete character'})
        
        # make favorite
        elif request.POST['_method'] == 'PUT':
            form = CharacterForm(request.POST)
            if form.is_valid():
                favorite_result = form.make_favorite(request)

                return HttpResponseRedirect(reverse('marvel:dashboard', args=()))
            else:
                return render(request, self.template_name, {'errormessage': 'error on make favorite'})


        # add character
        elif 'char_name' in request.POST:
            form = CharacterForm(request.POST)
            if form.is_valid():
                add_result = form.add(request)

                return HttpResponseRedirect(reverse('marvel:dashboard', args=()))
            else:
                return render(request, self.template_name, {'errormessage': errormessage})

mysite/marvel/views/dashboard_view.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from .forms.search_character_form import SearchCharacterForm
from .forms.character_form import CharacterForm

from ..models.user_characters import UserCharacters

class DashboardView(LoginRequiredMixin, View):
    form_class = SearchCharacterForm
    template_name = 'marvel/dashboard.html'
    login_url = '/marvel/'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        form_search = self.form_class()
        form_add = CharacterForm()
        my_characters = []

        # Renderiza as informações do Dashboard
        user_first_name = request.user.first_name
        user_characters = UserCharacters.objects.filter(user=request.user.useraccount)

        for item in user_characters:
            my_characters.append({'char_external_url': item.character.char_external_url,
                                  'image_url': item.character.image_url,
                                  'char_name': item.character.char_name,
                                  'description': item.character.description,
                                  'avaliable_comics': item.character.avaliable_comics,
                                  'is_favorite': item.is_favorite,
                                  'char_id': item.character.id
                                })           

        return render(request, self.template_name, {'user_first_name': user_first_name,
                                                    'my_characters': my_characters,
                                                    'form_search': form_search,
                                                    'form_add': form_add})

mysite/marvel/views/home_login_view.py
from django.views import View
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login

from .forms.login_form import LoginForm

class HomeLoginView(View):
    form_class = LoginForm
    template_name = 'marvel/home_login_template.html'

    def get(self, request, *args, **kwargs):

        # se ja esta autenticado redireciona para o dashboard
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('marvel:dashboard', args=()))
        else:  
            # senao renderiza o formulario
            form = self.form_class()
            return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        errormessage = ''

        # verifica se o form é valido
        if form.is_valid():
            
            # verifica usuario/senha
            username = username=form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            # retorna resultado de sucesso ou falha no login
            if user is not None:
                
                # atualiza a session
                request.session.update({'username': username})
                
                # loga o usuario
                login(request, user)

                # redireciona para o Dashboard
                return HttpResponseRedirect(reverse('marvel:dashboard', args=()))
            else:
                errormessage = 'Invalid Credentials'
        else:
            errormessage = 'Invalid form data'

        # renderiza a pagina com a mensagem de erro
        return render(request, self.template_name, {'form': form, 
                                                    'errormessage': errormessage})

mysite/marvel/views/logout_view.py
from django.views import View
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout

class LogoutView(View):

    def get(self, request, *args, **kwargs):
        
        # desloga o usuario
        logout(request)

        return HttpResponseRedirect(reverse('marvel:home_login', args=()))

mysite/marvel/views/search_character_view.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from .forms.search_character_form import SearchCharacterForm

class SearchCharacterView(LoginRequiredMixin, View):
    form_class = SearchCharacterForm
    template_name = 'marvel/dashboard.html'
    login_url = '/marvel/'
    redirect_field_name = 'redirect_to'

    def post(self, request, *args, **kwargs):
        errormessage = ''
        data = []
        form = self.form_class()

        search_result = {}
        if 'char_name_search' in request.POST:
            form_search = SearchCharacterForm(request.POST)
            if form_search.is_valid():
                search_result = form_search.search()

                # se encontrou resultado na api
                if search_result['success']:

                    # parse dos dados dos personagens
                    for results in search_result['data']['results']:

                        external_id = results['id']
                        name = results['name']
                        description = results['description']
                        image = results['thumbnail']['path']
                        image += '.'+results['thumbnail']['extension']
                        comics_available = results['comics']['available']
                        comics_list = [items['name'] for items in results['comics']['items']]
                        resources = [items for items in results['urls']]
                        external_url = results['urls'][0]['url']

                        data.append({ 'external_id': external_id,
                                'name': name,
                                'description': description,
                                'image': image,
                                'comics_available': comics_available,
                                'comics_list': comics_list,
                                'resources': resources,
                                'external_url': external_url
                        })
                else:
                    errormessage = search_result['message']

        return render(request, self.template_name, {'form_search': form, 
                                                    'user_first_name': request.user.first_name,
                                                    'errormessage': errormessage, 
                                                    'search_result': data})

mysite/marvel/templates/marvel/dashboard.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Marvel Dashboard</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static "marvel/assets/css/main.css" %}" />
	</head>
	<body id="top">

        <section id="banner" style="" data-video="image/banner">
            <div class="inner">
                <header>
                    <h1>Dashboard</h1>
                    <a href="{% url 'marvel:logout' %}">logout</a>
                    <p>Welcome <b>{{user_first_name}}</b>. This is your Dashboard!</p>
                    <p>Enjoy your collection of {{my_characters|length}} characters</p>

                    <p>To add more characters, please use the search:</p>
					<a href="#main" class="more">Learn More</a>

                </header>
            </div>
        </section>

			<!-- Main -->
				<div id="main">
                    <h2>My Collection</h2>

					<div class="inner">

					<!-- Boxes -->
						<div class="thumbnails">

                            {% for item in my_characters%}
                                   <div class="box">
                                    <a href="{{ item.char_external_url }}" class="image fit"><img src="{{ item.image_url }}" alt="Image of {{ item.char_name }}" /></a>
                                    <div class="inner">
                                        <h3>{{ item.char_name }} {% if item.is_favorite %}<span>* Favorite *</span>{% endif %}</h3>
                                        <p>{% if item.description %}{{ item.description }}{% endif %}</p>
                                        <p>Avaliable Comics: <b>{{ item.avaliable_comics }}</b></p>
                                        <a href="{{ item.char_external_url }}" class="button fit" target="_blank">More Info</a>


                                        <form action="{% url 'marvel:character' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="char_id" value="{{ item.char_id }}">                                            
                                            <input type="hidden" name="_method" value="PUT">
                                            <input type="submit" value="Make Favorite" class="button fit green">
                                        </form>

                                        <form action="{% url 'marvel:character' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="char_id" value="{{ item.char_id }}">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="submit" value="Remove from Collection" class="button fit red">
                                        </form>

                                    </div>
                                </div>

                            {% endfor %}
						</div>

					</div>
				</div>

			<!-- Footer -->
				<footer id="footer">
					<div class="inner">
                        <h4>Find more Marvel's Characters</h4>
                        <form action="{% url 'marvel:search_character' %}" method="post">
                            {% csrf_token %}
                            {{ form_search }}
                            <br/>
                            <input type="submit" value="Submit">
                        </form>
                        <span>{{ errormessage }}</span>
					</div>
				</footer>

                {% if not errormessage %}
    				<footer id="footer-results">
                        <div class="thumbnails">
                        {% for item in search_result %}
                            <div class="box">
                                    <img src='{{ item.image }}' style="width:80px"/>
                                    <li>Name: {{ item.name }}</li>
                                    <li><p>Description: {{ item.description }}</p></li>
                                    <li><p>Total commics avaliable: {{ item.comics_available }}</p></li>
                                    <li><p>Comics list (first 20)</li>
                                    <ul>
                                    {% for comics in item.comics_list%}
                                        <li>{{ comics }}</li>
                                    {% endfor %}
                                    </ul>
                                    <li><p>Resources</li>
                                    <ul>
                                    {% for res in item.resources%}
                                        <li><a href='{{res.url}}' target='_blank'>{{ res.type }}</a></li>                                
                                    {% endfor %}
                                    </ul>
                                <form action="{% url 'marvel:character' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="_method" value="POST">
                                    <input type="hidden" id="char_name" name="char_name" value="{{ item.name }}" />
                                    <input type="hidden" id="char_id" name="char_id" value="{{ item.external_id }}" />
                                    <input type="hidden" id="char_external_url" name="char_external_url" value="{{ item.external_url }}" />
                                    <input type="hidden" id="image_url" name="image_url" value="{{ item.image }}" />
                                    <input type="hidden" id="description" name="description" value="{{ item.description }}" />                
                                    <input type="hidden" id="avaliable_comics" name="avaliable_comics" value="{{ item.comics_available }}" />                
                                    <input type="submit" value="Add {{ item.name }} do My Characters">
                                </form>
                            </div>
                        {% endfor %}
                        </div>
                    </footer>
                {% endif %}

		<!-- Scripts -->
			<script src='{% static "marvel/assets/js/jquery.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/jquery.scrolly.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/jquery.poptrox.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/skel.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/util.js" %}'></script>
			<script src='{% static "marvel/assets/js/main.js" %}'></script>

            <script language="javascript">
                    {% for item in my_characters%}
                        {% if item.is_favorite %}
                            $( document ).ready(function() {
                                $("#banner").attr("style", "background-image: url('{{item.image_url}}')");
                            })
                        {% endif %}                            
                    {% endfor %}            
            </script>

	</body>
</html>

mysite/marvel/templates/marvel/home_login_template.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Marvel Dashboard Login</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static "marvel/assets/css/main.css" %}" />
	</head>
	<body id="top">

        <section id="banner" style="" data-video="image/banner">
            <div class="inner">
                <header>
                    <h1>Login</h1>
                    {% if errormessage %}{{ errormessage }}{% endif %}
                    <form action="{% url 'marvel:home_login' %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <br/>
                        <input type="submit" value="Submit">
                    </form>
					<p>Try: <br/>
					user: guest<br/>
					password: django1234
					<br/>
					<span>;)</span>
					</p>
                </header>
            </div>
        </section>

			<!-- Footer -->
				<footer id="footer">
					<div class="inner">
                        <h4>Make a Awesome Marvel Collection --Using Django</h4>
					</div>
				</footer>
		<!-- Scripts -->
			<script src='{% static "marvel/assets/js/jquery.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/jquery.scrolly.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/jquery.poptrox.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/skel.min.js" %}'></script>
			<script src='{% static "marvel/assets/js/util.js" %}'></script>
			<script src='{% static "marvel/assets/js/main.js" %}'></script>

	</body>
</html>